name: lab-man

services:
  db:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ./src/lib/server/db/dockerfile
    environment: 
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-lab-man}
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  website:
    restart: unless-stopped
    build: 
      context: .
      args:
        NODE_ENV: production
        WEB_PORT: ${WEB_PORT}
        ORIGIN: ${ORIGIN}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db

volumes:
  pgdata: