name: lab-man

services:
  db:
    extends:
      file: compose.yml
      service: db

  website:
    extends:
      file: compose.yml
      service: website
    build:
      context: .
      args:
        NODE_ENV: development
        PORT: 5173
    environment:
      - NODE_ENV=development
      - PORT=5173
    ports:
      - "5173:5173"
      - "9229:9229"  # Debug port
    command: node --inspect=0.0.0.0:9229 ./node_modules/vite/bin/vite.js dev --host --port 5173
    develop:
      watch:
        - path: ./src
          target: /lab-man/src
          action: sync
        - path: ./static
          target: /lab-man/static
          action: sync
        - path: package.json
          target: /lab-man/package.json
          action: sync
        - path: pnpm-lock.yaml
          target: /lab-man/pnpm-lock.yaml
          action: sync

volumes:
  pgdata:
